### ISSUE TITLE
discord link under image not working..  page 11/ch4

### ISSUE THREAD

**Issue by MIKEGOOD-ETH** [volkyeth/nouns101#47]
discord link under image not working..  page 11/ch4

**Comment by volkyeth** [comment]
It's working for me 🤔 

This one, right? 
<img width="367" alt="image" src="https://user-images.githubusercontent.com/847070/210630836-e6d9d885-d867-4417-9c54-456efc89ae3a.png">

**Comment by MIKEGOOD-ETH** [comment]
Not the link, we wanted to attach the link under the Image so you can click the image. That isnt working.

**Comment by MIKEGOOD-ETH** [comment]
but not needed, its fine the way it is IMO.. lets keep it moving
