### ISSUE TITLE
About Page 

### ISSUE THREAD

**Issue by MIKEGOOD-ETH** [volkyeth/nouns101#48]
Can we add a button for an About page down in the footer next to the Nouns 101 logo so i can drop some text? I can give you the text in a google doc and we can add a little image for each of us, with links to our link trees or websites? 

Then have like a paragraph on lil noun funding us, etc..

**Comment by volkyeth** [comment]
There's this one Zylag made:
![image](https://user-images.githubusercontent.com/847070/210630655-27ae4e7c-cb9e-4d10-8305-b386bf7367b6.png)
